# Generated by Django 4.1 on 2024-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0002_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
